for i,v in next,getgc(true) do
    if type(v) == 'table' and rawget(v, 'Ammo') then
        setreadonly(v, false)
        rawset(v, 'Zoom', 30)
        rawset(v, 'Zoom2', 30)
        rawset(v, 'Ammo', math.huge)
        rawset(v, 'StoredAmmo', math.huge)
        rawset(v, 'MaxStoredAmmo', math.huge)
        rawset(v.FireModes, 'ChangeFiremode', false)
        rawset(v.FireModes, 'Semi', false)
        rawset(v.FireModes, 'Burst', false)
        rawset(v.FireModes, 'Auto', true)
        rawset(v.camRecoil, 'camRecoilUp', { 0, 0 })
        rawset(v.camRecoil, 'camRecoilTilt', { 0, 0 })
        rawset(v.camRecoil, 'camRecoilLeft', { 0, 0 })
        rawset(v.camRecoil, 'camRecoilRight', { 0, 0 })
        rawset(v.gunRecoil, 'gunRecoilUp', { 0, 0 })
        rawset(v.gunRecoil, 'gunRecoilTilt', { 0, 0 })
        rawset(v.gunRecoil, 'gunRecoilLeft', { 0, 0 })
        rawset(v.gunRecoil, 'gunRecoilRight', { 0, 0 })
        rawset(v, 'MinSpread', 0)
        rawset(v, 'MaxSpread', 0)
        rawset(v, 'MuzzleVelocity', 2500)
        rawset(v, 'BulletDrop', 0)
        rawset(v, 'CanBreak', false)
        rawset(v, 'adsTime', 0)
        rawset(v, 'RainbowMode', true)
        rawset(v, 'canAim', true)
        rawset(v, 'ShootType', 3)
    end
end
